change port

diff --git a/.github/workflows/deploy-wordpress.yml b/.github/workflows/deploy-wordpress.yml
--- a/.github/workflows/deploy-wordpress.yml
+++ b/.github/workflows/deploy-wordpress.yml
@@ -133,7 +133,15 @@ jobs:
             WP_CONTAINER=$(sudo docker ps -q --filter "name=wordpress_${INSTANCE_ID}")
             echo "Container ID: ${WP_CONTAINER}"
             sudo docker exec -i ${WP_CONTAINER} sh -c "ls /bitnami/wordpress/wp-content/plugins"
+            #sudo docker cp /home/bitnami/test_deploy ${WP_CONTAINER}:/bitnami/wordpress/wp-content/plugins/test_deploy
+
+            # Copy plugin to the WordPress container
             sudo docker cp /home/bitnami/test_deploy ${WP_CONTAINER}:/bitnami/wordpress/wp-content/plugins/test_deploy
+            if [ $? -eq 0 ]; then
+              echo "Plugin test_deploy copied successfully to ${WP_CONTAINER}"
+            else
+              echo "Failed to copy plugin test_deploy to ${WP_CONTAINER}"
+            fi
             sleep 30 # wait for the file copy
             sudo docker exec -i ${WP_CONTAINER} sh -c "ls /bitnami/wordpress/wp-content/plugins"
             sudo docker exec -i ${WP_CONTAINER} sh -c "wp plugin activate test_deploy --allow-root"
